### ISSUE TITLE
renv problem on Mac: the Matrix package cannot be installed

### ISSUE THREAD

**Issue by EmiliaJarochowska** [MindTheGap-ERC/CarbonateStratPalEvo#22]
`renv::restore()` tries to compile Matrix from sources, but crashes. Attached the log - as much as I could capture from the termninal. This follows the step where you agree to install missing packages. R 4.3.1
It is resolved by changing the version to `1.6-5` in `renv.lock` but I am yet to check if that breaks anything down because of other packages that won't load either

**Comment by NiklasHohmann** [comment]
@EmiliaJarochowska updated package versions in lockfile. Please try again and see if it works
